remote_theme: just-the-docs/just-the-docs

aux_links:
  "View on GitHub":
    - "https://github.com/snoidetx/Snoidepaedia"

aux_links_new_tab: true

footer_content: Copyright &copy;snoidetx. Updated on 31/05/2022.
