remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

permalink: pretty

aux_links:
  "View on GitHub":
    - "https://github.com/snoidetx/Snoidepaedia"

aux_links_new_tab: true

footer_content: Copyright &copy;snoidetx. Last updated on 15/06/2022 (v1.1.1).
