remote_theme: just-the-docs/just-the-docs

permalink: pretty

aux_links:
  "View on GitHub":
    - "https://github.com/snoidetx/Snoidepaedia"

aux_links_new_tab: true

footer_content: Copyright &copy;snoidetx. Last updated on 14/06/2022 (v1.0.0).
