remote_theme: just-the-docs/just-the-docs

aux_links:
  "View on GitHub":
    - "https://github.com/snoidetx/Snoidepaedia"

aux_links_new_tab: true

last_edit_timestamp: true
last_edit_time_format: "Copyright &copy;snoidetx. Last modified: %d/%m/%Y %H:%M."
