remote_theme: snoidetx/just-the-docs

plugins:
  - jekyll-remote-theme

permalink: pretty

classes: wide

aux_links:
  "View on GitHub":
    - "https://github.com/snoidetx/Snoidepaedia"

aux_links_new_tab: true

footer_content: Copyright &copy;snoidetx. Last updated on 31/08/2022 (v1.3.3).
