remote_theme: just-the-docs/just-the-docs

baseurl: "https://github.com/snoidetx/Snoidepaedia/tree/main/"

permalink: pretty

aux_links:
  "View on GitHub":
    - "https://github.com/snoidetx/Snoidepaedia"

aux_links_new_tab: true

footer_content: Copyright &copy;snoidetx. Updated on 01/06/2022.
