remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

permalink: pretty

classes: wide

aux_links:
  "View on GitHub":
    - "https://github.com/snoidetx/Snoidepaedia"

aux_links_new_tab: true

footer_content: Copyright &copy;snoidetx. Last updated on 22/06/2022 (v1.2.2).
