title: Snoídepaedia
description: Everything related to @snoidetx

remote_theme: snoidetx/just-the-docs

plugins:
  - jekyll-remote-theme

permalink: pretty

classes: wide

aux_links:
  "View on GitHub":
    - "https://github.com/snoidetx/Snoidepaedia"

aux_links_new_tab: true

footer_content: Copyright &copy;snoidetx. All contents and information are updated as on 2/11/2023.
