title: Snoídepaedia
description: Everything related to @snoidetx

remote_theme: snoidetx/just-the-docs

plugins:
  - jekyll-remote-theme

compress_html:
  blanklines: true

permalink: pretty

classes: wide

aux_links:
  "View on GitHub":
    - "https://github.com/snoidetx/Snoidepaedia"

aux_links_new_tab: true

color_scheme: snoidepaedia_color_scheme

footer_content: Copyright &copy;snoidetx. All contents and information are updated as on 30/10/2024.
